#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-xxtea
Version  : 1.0.11
Release  : 19
URL      : https://pecl.php.net//get/xxtea-1.0.11.tgz
Source0  : https://pecl.php.net//get/xxtea-1.0.11.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : buildreq-php

%description
# XXTEA 加密算法的 PHP 扩展实现
<a href="https://github.com/xxtea/">
<img src="https://avatars1.githubusercontent.com/u/6683159?v=3&s=86" alt="XXTEA logo" title="XXTEA" align="right" />
</a>

%prep
%setup -q -n xxtea-1.0.11
cd %{_builddir}/xxtea-1.0.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure --disable-static
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)
